apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  selector:
    matchLabels:
      role: database
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
